<?php

$title = 'Delete Clientes';
$url   = $this->url('clientes', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Você tem certeza que quer deletar?
    "<?= $this->escapeHtml($clientes->nome) ?>" by
    "<?= $this->escapeHtml($clientes->funcao) ?>"?
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $clientes->id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
    <input type="submit" class="btn btn-success" name="del" value="No" />
</div>
</form>