<?php

$title = 'Editar Cliente';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$nome = $form->get('nome');
$nome->setAttribute('class', 'form-control');
$nome->setAttribute('placeholder', 'Nome do cliente');

$funcao = $form->get('funcao');
$funcao->setAttribute('class', 'form-control');
$funcao->setAttribute('placeholder', 'Função');

$idade = $form->get('idade');
$idade->setAttribute('class', 'form-control');
$idade->setAttribute('placeholder', 'Idade do Cliente');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('clientes', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($nome) ?>
    <?= $this->formElement($nome) ?>
    <?= $this->formElementErrors()->render($nome, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($funcao) ?>
    <?= $this->formElement($funcao) ?>
    <?= $this->formElementErrors()->render($funcao, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($idade) ?>
    <?= $this->formElement($idade) ?>
    <?= $this->formElementErrors()->render($idade, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();